PenaltyWeight:              100.0

CircleObs:                  [  1.0, 0.0,
                               0.0, 1.0,
                               -1., 0.0,
                               0.0, -1.,
                               1.0, 0.0
                            ]

PieceLength:                0.3

RelCostTol:                 1.0e-6
